### ISSUE TITLE
리더기 및 sd카드가 작동하지 않는 문제

### ISSUE THREAD

**Issue by chphch** [hyojeonglee/osfall2019#17]
조교님 리더기 및 sd카드가 정상적으로 작동하지 않는데 지금 연구실에서 받을 수 있을까요?

늦은 시간 죄송합니다.

**Comment by hayunjong83** [comment]
안녕하세요
네 괜찮습니다.
302동 319호로 오셔서 조교들 찾아주시면 교환해 드리도록 하겠습니다.

감사합니다.
- 하윤종 드림.

2019년 10월 7일 (월) 오후 8:34, Hyunwoo Jung <notifications@github.com>님이 작성:
