### ISSUE TITLE
[필독] Project 1 Peer Review (~ 10/11 17시)

### ISSUE THREAD

**Issue by hyojeonglee** [hyojeonglee/osfall2019#23]
Peer review를 위한 [구글폼](https://forms.gle/EzASqWg7DAkK4gjS9)입니다. **10/11 17시**까지 제출해주세요.
**과제 1 진행시점 기준으로 1~2인팀은 제출하지 않으셔도 됩니다.**

**Comment by chphch** [comment]
팀원이 1명인 팀도 제출해야 하나요?

**Comment by lynring24** [comment]
제출하지 않으셔도 됩니다.  (**3명 이상**인 경우 작성하세요.)
