### ISSUE TITLE
Peer review (~ 10/11 17시) + 기기 관련 공지

### ISSUE THREAD

**Issue by hyojeonglee** [hyojeonglee/osfall2019#27]
- **Peer review 10/11 금요일 17시까지 꼭 제출**해주시고, (미제출시 기본점수만 부여되니 참고바랍니다. 팀 내에 제출안하신 팀원이 있는지 확인 부탁드립니다.)
- 조교들이 기기정리를 할 예정이라, **키트 혹은 구성품 2개 이상 소지하고 계신 분들은 연구실로 반납**해주시면 감사하겠습니다.

**Comment by kjp4155** [comment]
안녕하세요 조교님,

3조 피어리뷰 완료되었는지 확인해주실 수 있나요?

그리고 키트 1개 이상이면 전부 반납해야된다는 뜻인가요?

**Comment by hyojeonglee** [comment]
네, 3조 피어리뷰 완료되었습니다.
잘못 공지해서 해당 부분 수정했습니다~ 개인당 키트 혹은 구성품 2개 이상인 경우 반납해주시면 됩니다.

**Comment by hyunminch** [comment]
안녕하세요, 제가 5시보다 조금 늦게 피어 리뷰를 남겼는데 페널티가 있을까요?

**Comment by hyojeonglee** [comment]
@hyunminch 아뇨 없습니다~ 어제 오후에 일괄적으로 제출 여부 확인했습니다.
