### ISSUE TITLE
Project 2 디자인 리뷰 신청 공지 (신청기한: ~ 10/24 11 AM)

### ISSUE THREAD

**Issue by hyojeonglee** [hyojeonglee/osfall2019#28]
이번 주 목요일(10/24) project 2 디자인 리뷰 [신청폼](https://forms.gle/csTnEMUnG3q5bLsa9)입니다.
팀원들과 함께 리뷰 참여 여부 및 시간을 상의해서 팀대표 한 분이 신청해주세요.
project 2의 디자인 방향 등을 미리 구상해보시고, 제약조건 등 질문할 것들을 생각해서 오시면 됩니다.
24일 오전 11시까지 받도록하겠습니다.

**Comment by kjp4155** [comment]
안녕하세요 조교님.

목요일 수업은 따로 없고 디자인 리뷰가 진행되는건가요?

만약 아직 질문이 없으면 참석하지 않아도 되나요?

**Comment by hyojeonglee** [comment]
@kjp4155 네 이론수업은 아니고 과제를 위한 디자인리뷰(실습수업)가 진행됩니다. 따로 출석체크를 하지는 않겠지만, 구현에 대한 구체적인 질문 뿐 아니라 디자인 방향에 대한 간단한 질문도 괜찮으니 참석하시면 더 좋을 것 같습니다.
