### ISSUE TITLE
우분투에서 크로스 컴파일 시 헤더 경로 설정 관련

### ISSUE THREAD

**Issue by hyunminch** [hyojeonglee/osfall2019#3]
안녕하세요,

우분투에서 Project1용 test 코드를 작성하고, `arm-linux-gnueabi-gcc`를 이용해 바이너리를 생성하려고 할 때, kernel 경로를 include 함에 있어 잘 모르겠는 게 있어 여쭤봅니다.
추가해야되는 kernel 경로가 repository의 include/에 있는 것(소스 그대로)일까요? 아니면, 새롭게 빌드된 커널 어딘가에 있는 헤더 파일들을 찾아야 하는 걸까요?

감사합니다.

**Comment by hyojeonglee** [comment]
네, 커널 경로는 repository의 include를 그대로 쓰시면 됩니다.

**Comment by hyunminch** [comment]
넵 감사합니다!
