### ISSUE TITLE
[개발 환경 설정] screen으로 rasberry-pi 접속후 로그인 시 검정 화면 현상

### ISSUE THREAD

**Issue by chphch** [hyojeonglee/osfall2019#4]
개발 환경 설정 관련 질문입니다.

serial2usb로 rasberry-pi와 laptop을 연결하고 ```sudo screen /dev/ttyUSB0 115200``` 으로 접속하면 타이젠 부팅이 시작되는 것을 볼 수 있습니다.

그런데 로그인을 위해 ctrl+alt+f2를 입력하면 검정색 화면이 나타나면서 어떤 키도 입력되지 않습니다.

어떻게 하면 좋을까요?

**Comment by lynring24** [comment]
로그인을 위해 ``` ctrl+alt+f2```을 입력하는 과정은 **모니터와 HDMI 케이블**로 접속할 때 사용하는 것이고,  screen에서는 사용하지 않습니다. 자료대로 screen 부분까지 수행했다면 부팅 후 로그인 화면이 나옵니다.  수행 후에 여전히 검정 화면이 나타났다면, serial 케이블 및 기계의 문제일 수 있습니다.

**Comment by chphch** [comment]
감사합니다!
