### ISSUE TITLE
Multiple Definition Error: get_gps_location

### ISSUE THREAD

**Issue by chphch** [hyojeonglee/osfall2019#46]
조교님,

아래와 같은 에러는 어떻게 해결해야 할까요?

![image](https://user-images.githubusercontent.com/19252487/69774146-70b8f880-11d8-11ea-8021-11daf9564076.png)

**Comment by hyojeonglee** [comment]
Makefile 등에서 에러에 나타난 파일들 간에 dependency를 확인해보고 헤더파일이 중복으로 include되진 않았는지 확인해보시길 바랍니다. 
그런데 위에 나타난 파일들에서 해당 시스템콜들이 필요한지는 다시 한번 생각해보시면 좋겠습니다.

**Comment by chphch** [comment]
앗 함수를 잘못된 곳에 정의한 사소한 실수였습니다. 번거롭게 해서 죄송합니다.
