### ISSUE TITLE
How to get rasberry-pi IP?

### ISSUE THREAD

**Issue by chphch** [hyojeonglee/osfall2019#7]
rasberry-pi IP설정 방법에 대해 조금 더 구체적으로 설명해주실 수 있나요?

아래 링크 읽어보았는데 잘 이해가 되지 않습니다.
https://github.com/hyojeonglee/osfall2019/blob/master/presentations/DevelopmentEnvironmentandDebuggingTips.pdf

ifconfig 명령어 입력했을 때에는 IP가 나오지 않네요

**Comment by hayunjong83** [comment]
안녕하세요-
질문 주셨던 것처럼 ifconfig 의 결과 IP가 나오지 않는 것은, 현재 저희가 실습중인 타이젠OS에서 DHCP 서비스를 자동적으로 지원해주지 않기 때문입니다. 따라서 환경설정문서에 나온 것처럼 인터넷 연결을 하거나, 랜 다이렉트 연결을 원하시는 경우에는 static ip를 직접 설정해주셔야 합니다. 
참고로 타이젠os에서 고정 ip 설정은 Connman 패키지를 이용하거나 스크립트를 이용해서 설정할 수 있습니다. 
https://thangamaniarun.wordpress.com/2014/02/09/how-to-assign-static-ip-address-manually-in-tizen-or-meego-based-ivi-operating-systems/
https://stackoverflow.com/questions/21979560/configuring-static-ip-address-for-tizen-os

하지만 현재 저희가 실습 중인 사항은 System call 추가 등을 통한 OS의 동작원리 이해에 초점이 맞춰져 있어서, 위의 사항을 직접 실행해 볼 때 필요한 패키지들이 설치되어 있지는 않습니다. 따라서 환경설정 문서에 나와있는 부분은 Raspbian이나 Ubuntu Mate같은 라즈베리 파이에서 사용할 수 있는 다른 OS에서 실습할 때, 참고하실 부분으로 이해해주시면 감사하겠습니다.

문서에 나와있는 시리얼 통신이나 hdmi 연결이 앞으로의 실습을 진행하실 때에는 더 유용할 것으로 생각하고 있습니다. 혹시 두 가지 방법으로 실습이 어려우실 경우나 ip설정을 통한 연결을 꼭 실습해보신 경우에 추가 질문 주시면 다시 답변드리도록 하겠습니다.
감사합니다.
